### ISSUE TITLE
Keyboard Locking/Passwort Protection

### ISSUE THREAD

**Issue by c0zmo** [hbekel/keyman64#1]
Lock the C64 until a password is entered

By using a designated command (i.e. 'LOCK'), Keyman64 stops relaying keystrokes to the C64, until a password is entered. A second command (i. e. 'SETPASSWORD') is used to let the user enter the password. The C64's BASIC prompt could be used for providing the necessary feedback.

Mock-up of the pwchange procedure:

READY. <meta+p>
ENTER NEW PASSWORD: *****\* <RETURN>
RE-ENTER NEW PASSWORD: *****\* <RETURN>
PASSWORD HAS BEEN CHANGED.

**Comment by hbekel** [comment]
Yes, that should be possible. I'll look into it.

**Comment by hbekel** [comment]
I have now implemented a first draft of this feature in [3aeda8f](https://github.com/hbekel/keyman64/commit/3aeda8f0404f5c20ad6e31fbc8c898e8cb7f3f79). 

See the commit message for details.
